### PR TITLE
added basic support for epel7

### PR DESCRIPTION
**Pull request by BOPOHA**
include shared lib in package, added RPath to find it
small refactoring, remove all the environs
clean unused environs
c7: fix make test
init rpm c7

### CODE REVIEW

**Comment by BOPOHA** [comment]
@NickJH 
i haven't tested this properly, but it should work.

```
# yum install stellar-core-18.5.0-8.el7.x86_64.rpm stellar-system-0.0.6-2.el7.x86_64.rpm -y
# ldd /usr/bin/stellar-core | head -n3
	linux-vdso.so.1 =>  (0x00007ffd4a132000)
	libpq.so.rh-postgresql12-5 => /usr/share/stellar/lib/libpq.so.rh-postgresql12-5 (0x00007f2b3dd81000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f2b3da79000)
# /usr/bin/stellar-core version
18.5.0-8.el7
#
```

**Comment by NickJH** [comment]
I have a question about EPEL policy. Are you allowed to put into EPEL packages depending on SCL packages? I didn't think you were. For that reason Nextcloud couldn't be updated because it required an SCL version of PHP.

**Comment by BOPOHA** [comment]
> I have a question about EPEL policy. Are you allowed to put into EPEL packages depending on SCL packages? I didn't think you were. For that reason Nextcloud couldn't be updated because it required an SCL version of PHP.


I understand that you are talking about some legal things.
But I don't understand what exactly you mean.

rpm package has not  dependencies on SCL at all.
I "stole" the .so file from the SCL and put it in my package, in a separate folder that only the built application knows about.
i build rpm packages with COPR (1).
and, I do not know the legal restrictions on these actions.


I already have repo for builddependencies (2), 
and i think i can rebuild rh-postgresql12-postgresql if it will be required. 

(1) https://copr.fedorainfracloud.org/coprs/vorona/stellar-packages/monitor/
(2) https://copr.fedorainfracloud.org/coprs/vorona/stellar-packages-build-dependencies/

**Comment by NickJH** [comment]
It is not a legal thing I am questioning, more an EPEL policy thing. For Stellar Core to work, you will need a `Requires: rh-postgresql12` (or 10 or 13 depending on what you build against) in the spec file as a dependency. This is a Requires of an SCL package and I don't think EPEL allow that. You will need to ask on the EPEL mailing list.

**Comment by BOPOHA** [comment]
In my case there is no "Requires" in spec, I am only using "BuildRequires".
as result i dont need any of the sclo/rh repos to install and run stellar-core.
See proof bellow.
But if you are speaking about `EPEL Package Request`, it make sense to think about and i have not answer.


```shell
$ podman run -it --rm centos:7
[root@1a75417ed537 /]# yum repolist -q
repo id                                      repo name                                      status
base/7/x86_64                                CentOS-7 - Base                                10072
extras/7/x86_64                              CentOS-7 - Extras                                509
updates/7/x86_64                             CentOS-7 - Updates                              3730
[root@1a75417ed537 /]# curl -s https://copr.fedorainfracloud.org/coprs/vorona/stellar-packages/repo/epel-7/vorona-stellar-packages-epel-7.repo -o /etc/yum.repos.d/stellar.repo
[root@1a75417ed537 /]# yum install stellar-core stellar-system -y
==================================================================================================
 Package        Arch   Version       Repository                                              Size
==================================================================================================
Installing:
 stellar-core   x86_64 19.0.1-1.el7  copr:copr.fedorainfracloud.org:vorona:stellar-packages 6.6 M
 stellar-system x86_64 0.0.6-3.el7   copr:copr.fedorainfracloud.org:vorona:stellar-packages 3.7 k

Transaction Summary
==================================================================================================
Install  2 Packages
Running transaction
  Installing : stellar-system-0.0.6-3.el7.x86_64                                              1/2 
  Installing : stellar-core-19.0.1-1.el7.x86_64                                               2/2 
  Verifying  : stellar-core-19.0.1-1.el7.x86_64                                               1/2 
  Verifying  : stellar-system-0.0.6-3.el7.x86_64                                              2/2 

Installed:
  stellar-core.x86_64 0:19.0.1-1.el7              stellar-system.x86_64 0:0.0.6-3.el7             

Complete!
[root@1a75417ed537 /]# stellar-core version
19.0.1-1.el7
[root@1a75417ed537 /]# ldd /usr/bin/stellar-core
	linux-vdso.so.1 =>  (0x00007ffe5f1e1000)
	libpq.so.rh-postgresql12-5 => /usr/share/stellar/lib/libpq.so.rh-postgresql12-5 (0x00007f68df911000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f68df609000)
...
```

**Comment by NickJH** [comment]
And then, if you want to use postgres it is a manual decision? I see.

BTW, when I built it, I excluded the static build of libsodium and added `Requires: libsodium` and `BuildRequires: libsodium-devel`.

**Pull request merged**
